Added lecture files + added name of round-table
haam-community/haam-summer-school pull request #16
Opened 2024-07-17 16:55 UTC by bamorim-bio

#13

2024-07-18 07:27 UTC, TCLamnidis requested changes
The rendering looks good! 
I think it would be easier to navigate this if it were in sequence, Day 1 -> Day 2 -> Day3, instead of separating theoretical, practical and round table sessions. We could denote the type of session in the title, or with an emoji or sth. :)

2024-07-18 07:27 UTC, TCLamnidis commented on docs/2024/README.md
> +- **Round table** Unsupervised clustering analyses & Ancient DNA: _Jazmín Ramos-Madrigal_
This should be moved to the practical sessions. Jazmín joined for the roundtable as well, but she ran a proper practical session, which is where the slides are from.

2024-07-18 21:36 UTC, bamorim-bio commented
Check if there's anything else you'd like me to change? :)

2024-07-22 11:16 UTC, TCLamnidis approved these changes

2024-07-22 11:19 UTC, TCLamnidis commented
Made some tweaks:
 - Marked Robert's session as Theoretical. Was originally planned as a practical session, but due to technical issues it ended up being a lecture instead. 
 - Changed the Day 3 round-table title. and noted that Robert also joined.
 - Added a short explanation to title colours in teaching material page.
 - minor tweaks to HTML styling.

2024-07-22 11:19 UTC, merged